package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

/**
 * Userroles generated by hbm2java
 */
//import java.io.Serializable;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Chemicals implements java.io.Serializable
{

	
	private static final long serialVersionUID = 44444558L;
	private String id;
	private String sample;
	private String category;
	private String cas;
	private String toxpibio;
	private String toxpichemo;
	private String toxpibiochemo;

	//private Logger logger = LoggerFactory.getLogger(Chemicals.class);
	
			
	public Chemicals()
	{
		// logger.debug("\n-------\nReached Chemicals(); Main");
	}

	public Chemicals(String id, String sample, String category, String cas, String toxpibio,String toxpichemo)
	{
		//logger.debug("\n-------\nReached Chemicals(); Override 1");
		this.id = id;
		this.sample = sample;
		this.category = category;
		this.cas = cas;
		this.toxpibio = toxpibio;
		this.toxpichemo = toxpichemo;
	}

	public Chemicals(String id, String sample, String category, String cas, String toxpibio, String toxpichemo, String toxpibiochemo)
	{
		//logger.debug("\n-------\nReached Chemicals(); Override 2");
		this.id = id;
		this.sample = sample;
		this.category = category;
		this.cas = cas;
		this.toxpibio = toxpibio;
		this.toxpichemo = toxpichemo;
		this.toxpibiochemo = toxpibiochemo;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getSample()
	{
		return this.sample;
	}

	public void setSample(String sample)
	{
		this.sample = sample;
	}

	public String getCategory()
	{
		return this.category;
	}

	public void setCategory(String category)
	{
		this.category = category;
	}

	public String getCas()
	{
		return this.cas;
	}

	public void setCas(String cas)
	{
		this.cas = cas;
	}

	public String getToxpibio()
	{
		return this.toxpibio;
	}

	public void setToxpibio(String toxpibio)
	{
		this.toxpibio = toxpibio;
	}
	
	public String getToxpichemo()
	{
		return this.toxpichemo;
	}

	public void setToxpichemo(String toxpichemo)
	{
		this.toxpichemo = toxpichemo;
	}

	public String getToxpibiochemo()
	{
		return this.toxpibiochemo;
	}

	public void setToxpibiochemo(String toxpibiochemo)
	{
		this.toxpibiochemo = toxpibiochemo;
	}


}
